import { ConnectButton } from '@rainbow-me/rainbowkit'
import type { NextPage } from 'next'
import { useAccount } from 'wagmi'
import useDonateMe from '../hooks/useDonateMe'

import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { address, isConnected } = useAccount()
  const { mint, status, data } = useDonateMe()

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <br />
        {isConnected && (
          <button
            onClick={async () => {
              let tx = await mint?.()
              await tx?.wait()
            }}
          >donate me</button>
        )}
      </main>

      <footer className={styles.footer}>Made with @KevinFan</footer>
    </div>
  )
}

export default Home
